spring:
  datasource:
    url: jdbc:h2:mem:sb2023
    username: sb2023
    password:
  jpa:
    show-sql: true
    open-in-viem: false
    hibernate:
      ddl-auto: create #validale | update | create | create-srop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace:
          web-allow-others: false